name: merge_branch_name_check
on: 
  pull_request:
    types: [opened, reopened, synchronize]
    
jobs: 
  check-branch: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code
        uses: actions/checkout@v3 # リポジトリのコードをチェックアウトする
      - name: Check if PR is from allowed branch
        run: |
          sh ./scripts/checkPullRequestBranchName.sh
        env: 
          TO_BRANCH: ${{ github.event.pull_request.base.ref }}
          FROM_BRANCH: ${{ github.event.pull_request.head.ref }}
