name: Run gofmt and golangci-lint on Pull Request

on:
  pull_request:
    branches: develop

defaults:
  run:
    working-directory: ./go  # 作業ディレクトリを指定

jobs:
  go-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22' # Goのバージョンを指定

    - name: Install dependencies
      run: go mod tidy  # 依存関係をインストール

    - name: Run gofmt
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "Code is not formatted. Run gofmt."
          gofmt -d .
          exit 1
        fi

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.2
        golangci-lint version
    
    - name: Clean golangci-lint cache  # キャッシュをクリア
      run: golangci-lint cache clean

    - name: Run golangci-lint
      run: golangci-lint run
