name: Run Go Test and Coverage on Pull Request

on:
  pull_request:
    branches: develop

defaults:
  run:
    working-directory: ./go  # 作業ディレクトリを指定

jobs:
  gotest-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22' # Goのバージョンを指定

    - name: Install dependencies
      run: go mod tidy  # 依存関係をインストール

    - name: Run Go Test with Coverage
      run: go test ./... -v -coverprofile=coverage.out

    - name: Check Coverage
      run: |
        go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//' > coverage.txt
        coverage=$(cat coverage.txt)
        echo "Total coverage: $coverage%"
        if (( $(echo "$coverage < 80.0" | bc -l) )); then
          echo "Test coverage ($coverage%) is below 80%"
          exit 1
        fi
