name: Run JUnit and Coverage on Pull Request

on:
  pull_request:
    branches: develop

defaults:
  run:
    working-directory: ./spring-app  # 作業ディレクトリを指定

jobs:
  pytest-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Build and run tests
      run: ./gradlew clean test jacocoTestReport
    
    - name: Generate Jacoco report
      run: ./gradlew jacocoTestCoverageVerification