name: Java CI Workflow

on:
  pull_request:
    branches: develop

defaults:
  run:
    working-directory: ./spring-app  # 作業ディレクトリを指定

jobs:
  java-ci:
    runs-on: ubuntu-latest

    steps:
      # コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # JDK 17のセットアップ
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradleキャッシュの設定
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Spotlessのチェック
      - name: Run Spotless check
        run: ./gradlew spotlessCheck

      # Checkstyleの実行
      - name: Run Checkstyle
        run: ./gradlew check

      # JUnitテストとJacocoによるカバレッジレポートの実行
      - name: Run JUnit and generate coverage report
        run: ./gradlew clean test jacocoTestReport

      # Jacocoカバレッジレポートの検証
      - name: Verify Jacoco coverage
        run: ./gradlew jacocoTestCoverageVerification
