name: Python CI Workflow

on:
  pull_request:
    branches: develop

defaults:
  run:
    working-directory: ./python  # 作業ディレクトリを指定

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      # コードのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Pythonのセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Pythonのバージョンを指定

      # Ruffのインストール
      - name: Install Ruff
        run: python -m pip install ruff

      # RuffによるFormatチェック
      - name: Run Ruff (format)
        run: ruff format . --check --diff

      # RuffによるLintチェック
      - name: Run Ruff (lint)
        run: ruff check --output-format=github .

      # pipenvのインストール
      - name: Install pipenv
        run: python -m pip install pipenv

      # 依存関係のインストール
      - name: Install dependencies
        run: pipenv install

      # Pytestの実行とカバレッジチェック
      - name: Run Pytest with coverage
        run: pipenv run pytest --cov --cov-fail-under=80
