name: Run Pytest and Coverage on Pull Request

on:
  pull_request:
    branches: develop

defaults:
  run:
    working-directory: ./python  # 作業ディレクトリを指定

jobs:
  pytest-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Pythonのバージョンを指定

    - name: Install pipenv
      run: python -m pip install pipenv  # pipenvをインストール

    - name: Install dependencies
      run: pipenv install  # Pipfileから依存関係をインストール

    - name: Run Pytest with Coverage and Threshold
      run: pipenv run pytest --cov --cov-fail-under=80  # カバレッジが80%未満なら失敗
