name: Run Pytest and Coverage on Pull Request

on:
  pull_request:

defaults:
  run:
    working-directory: ./python

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Pythonのバージョンを指定

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Run Pytest
      run: pipenv run pytest -v

  coverage:
    runs-on: ubuntu-latest
    needs: test  # coverageはtestジョブが完了してから実行

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov  # カバレッジ計測ツールをインストール

    - name: Run Pytest with Coverage and Threshold
      run: pipenv run pytest --cov --cov-fail-under=80  # カバレッジが80%未満なら失敗
