name: Run RSpec on Pull Request

on:
  pull_request:
    branches: develop

defaults:
  run:
    working-directory: ./rails-app  # 作業ディレクトリを指定

jobs:
  gotest-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: bundle install  # 依存関係をインストール

    - name: Run RSpec tests with coverage
      run: |
        bundle exec rspec
