name: Run Vitest and Coverage on Pull Request

on:
  pull_request:

defaults:
  run:
    working-directory: ./react-app  # 作業ディレクトリを指定

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # 使用するNode.jsのバージョンを指定

    - name: Install dependencies
      run: yarn install  # 依存関係をインストール (package-lock.jsonに基づくクリーンインストール)
    
    - name: Run Vitest
      run: yarn vitest  # テストを実行